
int allEvenBits();
int test_allEvenBits();
int implication(int, int);
int test_implication(int, int);
int bitMask(int, int);
int test_bitMask(int, int);
int bitParity(int);
int test_bitParity(int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int divpwr2(int, int);
int test_divpwr2(int, int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
int greatestBitPos(int);
int test_greatestBitPos(int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int isTmax(int);
int test_isTmax(int);
int leftBitCount(int);
int test_leftBitCount(int);
int getByte(int, int);
int test_getByte(int, int);
int negate(int);
int test_negate(int);
int thirdBits();
int test_thirdBits();
int minusOne();
int test_minusOne();
int bitXor(int, int);
int test_bitXor(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int trueFiveEighths(int);
int test_trueFiveEighths(int);
